# pretrain_b02.yaml

data:
  raw_dir: "data/raw/B04"
  processed_dir: "data/processed/B04"
  sampling_rate: 128000
  highpass_freq: 2000     # 0 để tắt lọc (Học theo năng lượng Energy)
  patch_size: 2048     # Giá trị cũ
  stride: 1024         
  lookback: 4096       
  horizon: 1024        
  skip_ratio: 0.1
  train_ratio: 0.5

model:
  cnn_out_channels: 64
  mamba_d_model: 64
  mamba_n_layer: 4
  mamba_d_state: 16
  mamba_d_conv: 4
  mamba_expand: 2
  bidirectional: false
  decomp_kernel: 25

training:
  batch_size: 128
  learning_rate: 5e-4
  epochs: 50
  device: "cuda"

logging:
  project_name: "Hybrid_Mamba_CNN_B04"
  use_wandb: false
